# Generated by Django 4.1.5 on 2023-08-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0002_alter_products_main_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wg_id',
            field=models.IntegerField(null=True, verbose_name='Id товарной группы'),
        ),
    ]
