# Generated by Django 4.1.5 on 2023-08-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0003_alter_products_wg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wares_parent',
            field=models.IntegerField(null=True, verbose_name='Товар родитель'),
        ),
    ]
