# Generated by Django 4.1.5 on 2023-08-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0004_alter_products_wares_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код'),
        ),
    ]
