# Generated by Django 4.1.5 on 2023-08-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0005_alter_products_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='HandlerApp.productgroup'),
        ),
    ]
