# Generated by Django 4.1.5 on 2023-08-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0007_alter_products_wg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('barcode', models.CharField(max_length=255, null=True, verbose_name='Штрих-код')),
                ('group', models.CharField(max_length=255, verbose_name='Группа товара')),
                ('unit', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('quantity', models.IntegerField(verbose_name='Остаток')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.TextField(null=True, verbose_name='Изображение товара')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='wg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wg_name', to='HandlerApp.productgroup', verbose_name='Товарная группа'),
        ),
    ]
