# Generated by Django 4.1.5 on 2023-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0008_products1_alter_products_wg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products1',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
