# Generated by Django 4.1.5 on 2023-08-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0009_alter_products1_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products1',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
