# Generated by Django 4.1.5 on 2023-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0010_alter_products1_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products1',
            name='id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, unique=True),
        ),
    ]
