# Generated by Django 4.1.5 on 2023-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0011_alter_products1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products1',
            name='wares_id',
            field=models.IntegerField(null=True, verbose_name='Id товара для системы'),
        ),
    ]
