# Generated by Django 4.1.5 on 2023-08-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0012_products1_wares_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandlerApp.products1')),
            ],
            options={
                'verbose_name': 'Расход товара',
                'verbose_name_plural': 'Расход товара',
            },
        ),
    ]
