# Generated by Django 4.1.5 on 2023-08-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandlerApp', '0013_dailyexpenditure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyExpenditure',
        ),
    ]
